server:
  port: 9411

spring:
  application:
    name: zipkin-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
