server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath/, classpath/medicine, classpath/user, classpath/prescription,
